### ISSUE TITLE
Package installation not complete

### ISSUE THREAD

**Issue by ghost** [reneeb/otrs-ArticleCopyMoveDelete#1]
Hello,

Thank you for your work.

After installing the package, I have the following message 
Code: var::packagesetup::ArticleCopyMoveDelete could not be loaded: Can't locate var/packagesetup/ArticleCopyMoveDelete.pm in @INC (@INC contains: /opt/otrs/Custom /opt/otrs/Kernel/cpan-lib /opt/otrs/ /usr/local/lib/perl5 /usr/local/share/perl5 /usr/lib/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5 /usr/share/perl5 . /etc/httpd) at /opt/otrs//Kernel/System/ObjectManager.pm line 191.

I have retried the installation manually with same result.

Could you give me your installation procedure?

Thank you

Guillaume

**Comment by reneeb** [comment]
Thanks for filing this issue.

This issue was resolved with commits ae146efcc038ef47ec485c04fa79bb62c19068ff  and be16ebe8a75aef28ad18c793093d5c3203189984

**Comment by ghost** [comment]
I have tested the modification still not working. (example of issue below)

Backend ERROR: OTRS-CGI-10 Perl: 5.10.1 OS: linux Time: Fri Jun 24 09:37:23 2016
Message: ???
 RemoteAddress: 192.168.200.143
 RequestURI: /support/index.pl?Action=AgentArticleCopyMove;TicketID=336;ArticleID=2138;
 Traceback (25733): 
   Module: Kernel::System::Web::InterfaceAgent::Run Line: 194
   Module: ModPerl::ROOT::ModPerl::Registry::opt_otrs_bin_cgi_2dbin_index_2epl::handler Line: 40
   Module: (eval) (v1.99) Line: 204
   Module: ModPerl::RegistryCooker::run (v1.99) Line: 204
   Module: ModPerl::RegistryCooker::default_handler (v1.99) Line: 170
   Module: ModPerl::Registry::handler (v1.99) Line: 31

I think the file ArticleCopyMoveDelete.sopm has not been update to match your modification <File Location="var/packagesetup/AgentArticleCopyMove.pm" Permission="644"/>

How do you proceed with installation? On my side I use the otrs.Console.pl Dev::Package::Build and next I load the opm file generated 

in addition in the deloper manual  https://otrs.github.io/doc/manual/developer/stable/en/html/package-porting.html#package-porting-4-to-5, I found some change like the Kernel/Output/HTML restructured.

Regards,
Guillaume

**Comment by reneeb** [comment]
The transition for OTRS5 is still in progress. Once I've finished it, I will release it on OPAR...

**Comment by ghost** [comment]
Ok, thank you for the feedback
